name: 1. Build selected branch
run-name: Build ${{ github.ref_name }}

on:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  version:
    name: Version
    uses: ./.github/workflows/version.yml


