name: 11. Build master/hotfix (auto)

on:
  push:
    branches:
      - master
      - hotfix/*

jobs:
  version:
    name: Version
    uses: ./.github/workflows/version.yml

  tag:
    if: startsWith(needs.version.outputs.version, 'v')
    name: T
    uses: ./.github/workflows/tagging.yml
    needs:
      - version
    with:
      source: ${{ github.event.after }}
      tag: ${{ needs.version.outputs.version }}
      create-release: ${{ startsWith(needs.version.outputs.version, 'v') }}
    secrets: inherit
