name: "Changelog create (reusable)"

on:
  workflow_dispatch:
    inputs:
      fromTag:
        required: true
        type: string
        description: fromTag

      toTag:
        required: true
        type: string
        description: toTag

      create-release:
        required: false
        type: boolean
        default: true
        description: create-release

concurrency:
  group: tagging
  cancel-in-progress: false
     
jobs:

  release:
    name: Create ${{ inputs.tag }} release
    runs-on: ubuntu-latest
    if: inputs.create-release
    continue-on-error: true

    steps:
      - name: Create changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          fetchViaCommits: true
          exportCache: true
          fromTag: ${{ inputs.fromTag }}
          toTag: ${{ inputs.totag }}
        env:
          GITHUB_TOKEN: ${{ secrets.token  }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          tag_name: ${{ inputs.tag }}

      