name: "Tag repository (reusable)"

on:
  workflow_call:
    inputs:
      
      source:
        type: string
        required: true

      tag:
        required: true
        type: string

      create-release:
        required: false
        type: boolean
        default: false

concurrency:
  group: tagging
  cancel-in-progress: false
     
jobs:
  tag:
    name: Create ${{ inputs.tag }} tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.source }}
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            README.md

      - name: Set commit info
        run: |
          git config user.email "blabla@gmail.com"
          git config user.name "Tagger"
          
      - name: Tag repository
        run: |
          git tag -a ${{ inputs.tag }} -m "Automated build tag"
          git push --tags
          sleep 5s
      - name: Extract branch name
        shell: bash
        run: echo "${{ github.ref_name }}  ${{github.run_number}}" 


  release:
    name: Create ${{ inputs.tag }} release
    runs-on: ubuntu-latest
    if: inputs.create-release
    needs:
      - tag
    continue-on-error: true

    steps:
      - name: Create changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          fetchViaCommits: true
          exportCache: true
          toTag: ${{ inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.token  }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          tag_name: ${{ inputs.tag }}

      
