name: "Calculate version (reusable)"

on:
  workflow_call:
    outputs:
      version:
        description: "Calculated build version"
        value: ${{ jobs.calculate.outputs.version }}
        
concurrency:
  group: version-${{ github.ref }}
  cancel-in-progress: false

env:
  USE_TAGS: ${{ github.ref_name == 'master' ||  startsWith(github.ref_name, 'hotfix/') }}

jobs:
  calculate:
    name: Calculate
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ steps.calc.outputs.version }}

    #TODO: simple semver here
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        if: env.USE_TAGS == 'true'
        with:
          fetch-depth: 0
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            semver.sh

      - name: GitHub describe
        if: env.USE_TAGS == 'true'
        id: describe
        run: |
          VER=$(git describe --tags --abbrev=0)
          echo "tag=$VER" >> "$GITHUB_OUTPUT"

      - name: Perform calculations
        id: calc
        run: |
          VERSION=0
          if [[ ${{ github.ref_name }} =~ ^v[0-9]+.[0-9]+.[0-9]+$ ]]; then    
          VERSION="${{ github.ref_name }}"

          elif [[ ${{ github.event_name }} == "workflow_dispatch" ]]; then
            VERSION=m${{ github.run_number }}
          
          elif [[ ${{ github.event_name }} == "pull_request" ]]; then    
            VERSION="pr${{ github.event.number }}"
            
          elif [[ ${{ env.USE_TAGS }} == "true" ]]; then
            VERSION=$(bash semver.sh -q -v ${{ steps.describe.outputs.tag }} ${{ startsWith(github.ref_name, 'hotfix/') && '-h' || '' }})
          fi

          # Make sure hotfix tag won't make it into master
          [[ ${{ github.ref_name }} == "master" && $VERSION =~ "-" ]] && exit 1 || true

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Calculated version: $VERSION"
